version: '2'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.13
    container_name: jaeger-all-1.13
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 9411:9411
      - 16686:16686
      - 14268:14268
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411