version: '3'
services:
  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.7.9-alpine
    environment:
      INFLUXDB_UDP_ENABLED: "true"
      INFLUXDB_UDP_DATABASE: "udp_db"
    volumes:
      - ~/Apps/docker/docker_data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8089:8089/udp"
    networks:
      - tick-net

  # Define a Telegraf service
  telegraf:
    image: telegraf:1.12.5-alpine
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    networks:
      - tick-net

  # Define a Chronograf service
  chronograf:
    image: chronograf:1.7.14-alpine
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor
    networks:
      - tick-net

  # Define a Kapacitor service
  kapacitor:
    image: kapacitor:1.5.3-alpine
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    ports:
      - "9092:9092"
    networks:
      - tick-net

networks:
  tick-net:
    driver: "bridge"
